
spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/pip?useSSL=false&serverTimezone=UTC
    hikari:
      schema: pip
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

server:
  servlet:
    context-path: /pip

